### ISSUE TITLE
As a developer, I want to get and send data to the back end from the front end

### ISSUE THREAD

**Issue by rqualls** [mnsavage/pdf_parser_front_end#10]
- Create a hook using axios to send information to and from the endpoint
- The endpoint URL should be stored in config.json in S3 bucket
- Implement a loading symbol or use skeletons, maybe show progress if possible

**Comment by rqualls** [comment]
get request format/ example: https://github.com/mnsavage/pdf_parser_website/pull/7

I may wait to add axios to fe until I know how to format the post request

**Comment by themnsavage** [comment]
Here are the PRs for allowing front-end to call GET to upload API endpoint:
Website repo: https://github.com/mnsavage/pdf_parser_website/pull/11
Back-end repo: https://github.com/mnsavage/pdf_parser_back_end/pull/11
Front-end repo: https://github.com/mnsavage/pdf_parser_front_end/pull/15
